# Generated by Django 5.1.1 on 2024-09-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('Deluxe', 'Deluxe Bahceli Oda'), ('Standard', 'Standart Oda'), ('Suite', 'Suite Oda')], max_length=50)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=6)),
                ('availability', models.BooleanField(default=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
