# Generated by Django 5.1.1 on 2024-09-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_reservation_ozel_istek_alter_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='availability',
        ),
        migrations.AddField(
            model_name='room',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
