# Generated by Django 5.1.1 on 2024-09-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Deluxe', 'Deluxe Bahçeli Oda'), ('Standard', 'Standart Oda'), ('Suite', 'Suite Oda'), ('Deluxe cift', 'Deluxe Bahçeli Çift Kişilik Oda'), ('Standard cift', 'Standart Çift Kişilik Oda')], max_length=50),
        ),
    ]
