# Generated by Django 5.1.1 on 2024-09-22 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_room_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Ozel_istek',
            new_name='special_requests',
        ),
    ]
