# Generated by Django 5.1.1 on 2024-09-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_rename_ozel_istek_reservation_special_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_occupancy',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
